/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseSyncExternalStoreRouteImport } from './routes/use-sync-external-store'
import { Route as UseOptimisticRouteImport } from './routes/use-optimistic'
import { Route as UseImperativeHandleRouteImport } from './routes/use-imperative-handle'
import { Route as UseIdRouteImport } from './routes/use-id'
import { Route as UseDeferredValueRouteImport } from './routes/use-deferred-value'
import { Route as UseActionStateRouteImport } from './routes/use-action-state'
import { Route as SuspenseRouteImport } from './routes/suspense'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const UseSyncExternalStoreRoute = UseSyncExternalStoreRouteImport.update({
  id: '/use-sync-external-store',
  path: '/use-sync-external-store',
  getParentRoute: () => rootRouteImport,
} as any)
const UseOptimisticRoute = UseOptimisticRouteImport.update({
  id: '/use-optimistic',
  path: '/use-optimistic',
  getParentRoute: () => rootRouteImport,
} as any)
const UseImperativeHandleRoute = UseImperativeHandleRouteImport.update({
  id: '/use-imperative-handle',
  path: '/use-imperative-handle',
  getParentRoute: () => rootRouteImport,
} as any)
const UseIdRoute = UseIdRouteImport.update({
  id: '/use-id',
  path: '/use-id',
  getParentRoute: () => rootRouteImport,
} as any)
const UseDeferredValueRoute = UseDeferredValueRouteImport.update({
  id: '/use-deferred-value',
  path: '/use-deferred-value',
  getParentRoute: () => rootRouteImport,
} as any)
const UseActionStateRoute = UseActionStateRouteImport.update({
  id: '/use-action-state',
  path: '/use-action-state',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspenseRoute = SuspenseRouteImport.update({
  id: '/suspense',
  path: '/suspense',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/suspense': typeof SuspenseRoute
  '/use-action-state': typeof UseActionStateRoute
  '/use-deferred-value': typeof UseDeferredValueRoute
  '/use-id': typeof UseIdRoute
  '/use-imperative-handle': typeof UseImperativeHandleRoute
  '/use-optimistic': typeof UseOptimisticRoute
  '/use-sync-external-store': typeof UseSyncExternalStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/suspense': typeof SuspenseRoute
  '/use-action-state': typeof UseActionStateRoute
  '/use-deferred-value': typeof UseDeferredValueRoute
  '/use-id': typeof UseIdRoute
  '/use-imperative-handle': typeof UseImperativeHandleRoute
  '/use-optimistic': typeof UseOptimisticRoute
  '/use-sync-external-store': typeof UseSyncExternalStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/suspense': typeof SuspenseRoute
  '/use-action-state': typeof UseActionStateRoute
  '/use-deferred-value': typeof UseDeferredValueRoute
  '/use-id': typeof UseIdRoute
  '/use-imperative-handle': typeof UseImperativeHandleRoute
  '/use-optimistic': typeof UseOptimisticRoute
  '/use-sync-external-store': typeof UseSyncExternalStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/suspense'
    | '/use-action-state'
    | '/use-deferred-value'
    | '/use-id'
    | '/use-imperative-handle'
    | '/use-optimistic'
    | '/use-sync-external-store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/suspense'
    | '/use-action-state'
    | '/use-deferred-value'
    | '/use-id'
    | '/use-imperative-handle'
    | '/use-optimistic'
    | '/use-sync-external-store'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/suspense'
    | '/use-action-state'
    | '/use-deferred-value'
    | '/use-id'
    | '/use-imperative-handle'
    | '/use-optimistic'
    | '/use-sync-external-store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  SuspenseRoute: typeof SuspenseRoute
  UseActionStateRoute: typeof UseActionStateRoute
  UseDeferredValueRoute: typeof UseDeferredValueRoute
  UseIdRoute: typeof UseIdRoute
  UseImperativeHandleRoute: typeof UseImperativeHandleRoute
  UseOptimisticRoute: typeof UseOptimisticRoute
  UseSyncExternalStoreRoute: typeof UseSyncExternalStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-sync-external-store': {
      id: '/use-sync-external-store'
      path: '/use-sync-external-store'
      fullPath: '/use-sync-external-store'
      preLoaderRoute: typeof UseSyncExternalStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-optimistic': {
      id: '/use-optimistic'
      path: '/use-optimistic'
      fullPath: '/use-optimistic'
      preLoaderRoute: typeof UseOptimisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-imperative-handle': {
      id: '/use-imperative-handle'
      path: '/use-imperative-handle'
      fullPath: '/use-imperative-handle'
      preLoaderRoute: typeof UseImperativeHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-id': {
      id: '/use-id'
      path: '/use-id'
      fullPath: '/use-id'
      preLoaderRoute: typeof UseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-deferred-value': {
      id: '/use-deferred-value'
      path: '/use-deferred-value'
      fullPath: '/use-deferred-value'
      preLoaderRoute: typeof UseDeferredValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-action-state': {
      id: '/use-action-state'
      path: '/use-action-state'
      fullPath: '/use-action-state'
      preLoaderRoute: typeof UseActionStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspense': {
      id: '/suspense'
      path: '/suspense'
      fullPath: '/suspense'
      preLoaderRoute: typeof SuspenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  SuspenseRoute: SuspenseRoute,
  UseActionStateRoute: UseActionStateRoute,
  UseDeferredValueRoute: UseDeferredValueRoute,
  UseIdRoute: UseIdRoute,
  UseImperativeHandleRoute: UseImperativeHandleRoute,
  UseOptimisticRoute: UseOptimisticRoute,
  UseSyncExternalStoreRoute: UseSyncExternalStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
